# Generated by Django 6.0.1 on 2026-03-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'employee')},
        ),
    ]
